consul:
  image: bluemedorapublic/consul-rancher:0.8.0
  dns_search:
  - rancher.internal
  - ${DOMAIN}
  environment:
  - DC=${DC}
  - DNS=${DNS}
  - HTTPPORT=${HTTPPORT}
  - SERVERPORT=${SERVERPORT}
  - SERF_LANPORT=${SERF_LANPORT}
  - SERF_WANPORT=${SERF_WANPORT}
  volumes:
  - /opt/rancher/config
  - /opt/rancher/ssl
  - /var/consul
  labels:
    io.rancher.scheduler.affinity:host_label: dc=${DC}
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.dns: true
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name

